### PR TITLE
fix: make sure contributors have access to the correct information on forms

### LINKED ISSUE #1309: bug: Contributor users can't see/add relations in relationship form field selector
### What went wrong, step-by-step?
1. Visit a form that has a relation field as a contributor user
2. Click on the add relation button
3. No relations will appear

### What did you expect to happen?
Relations (filtered by type, if specified) should appear for the user, per our form-as-permission strategy.

### PR DESCRIPTION
**Pull request by tefkah**
## Issue(s) Resolved

Resolves #1309 

## High-level Explanation of PR

Previously the RelatedPubsPanel on a form would only show you the pubs that you were allowed to see when eg visiting the All Pubs page. This is too restrictive, forms are for providing a temporarily more privileged view for eg contributors, so the RelatedPubsPanel should show all Pubs matching the PubTypes defined on that form element.

To that end i created a new API endpoint, `/forms/:formSlug/:fieldSlug/pubs/:pubId?`

This returns all the pubs (barring any other filtering) matching the pubtypes set on the field with slug `:fieldSlug` on the form with slug `:formSlug`.
The optional pathparam `:pubId?` needs to be provided when updating the form. This should probably just be a `queryParam`, eg `?currentPubId`, kinda confusing.

Pubs are only returned if 
- For **creating** pubs
  - The user is a community editor or admin
  - The user is a community contributor with form access
- For **updating pubs**
	- The user is a comumnity editor or admin
	- The user is a contributor on that pub, and has access to at least one form.

#### Relation form elements now need to have at least one Pub Type defined before they show anything.

This is only mildly enforced when configuring the form. when you try to save a new relation form without configuring pubtypes, you get this error
	
image

Admins will see a warning when no pubtype has been configured 

image

#### new user hook

See here for showing the admin warning

https://github.com/pubpub/platform/blob/ff3cff3e140bd154ab45a2fd6ddfd1d33222b875/core/app/components/forms/elements/RelatedPubsElement.tsx#L193-L199 

#### Member table now shows what forms the user has access to

Makes it easier to debug contributor issues

image

#### Make the form switcher work

The form switcher now does something (previously it didnt).

The Update button now takes you to the correct form immediately.

## Test Plan

- Login as `none@pubpub.org`
- Try to create a Pub (Evaluation)
- Try to add an article
- You should see two Articles, no Evaluations.
- After creating the Eval, you should see the Articles in the related pubs table on the Pub detail page
- You should not be able to see any actions you can run on the article
- When clicking on the article, you should see a Not Authorized error

Maybe try a few more situations, but this is the gist. I intend to add some tests still.

### CODE REVIEW

File: core/app/api/v0/c/[communitySlug]/site/[...ts-rest]/route.ts [hunk 1]
```diff
@@ -794,6 +588,97 @@ const handler = createNextHandler(
...
+
+				// TODO: this does not account for permissions
+				responseHeaders.set(TOTAL_PUBS_COUNT_HEADER, `${pubCount}`);
+
+				return {
+					status: 200,
+					body: pubs,
+				};
+			},
+		},
```
Comment (tefkah) [inline core/app/api/v0/c/[communitySlug]/site/[...ts-rest]/route.ts:681]: this does practically the same as `pub.getMany`, but 
- checks whether the user has access to the form
- only gets the pubs that match the pubtype of that field on the form
- does not take into account the users permissions

**Comment by tefkah** [comment]
The PR is ready to look at, but ill still add some comments tomorrow!

File: core/app/c/[communitySlug]/pubs/[pubId]/page.tsx [hunk 2]
```diff
@@ -95,66 +115,78 @@ export default async function Page(props: {
...
+	const hasAccessToCurrentForm = !availableViewForms.find(
+		(form) => form.slug === formSlug || (form.isDefault && !formSlug)
+	);
+	const defaultForm = availableViewForms.find((form) => form.isDefault);
+	if (!hasAccessToCurrentForm) {
+		const redirectQuery = defaultForm ? "" : `?form=${availableViewForms[0].slug}`;
+
+		// redirect to first available form
+		redirect(`/c/${communitySlug}/pubs/${pub.id}/edit${redirectQuery}`);
+	}
```
Comment (tefkah) [inline core/app/c/[communitySlug]/pubs/[pubId]/page.tsx:146]: similar to the `edit` page, redirect users to the correct form if they can't access the current one

File: core/app/c/[communitySlug]/pubs/[pubId]/page.tsx [hunk 3]
```diff
@@ -166,11 +198,23 @@ export default async function Page(props: {
...
 	const { stage, ...slimPub } = pub;
 	const pubByForm = getPubByForm({ pub, form, withExtraPubValues });
+
+	const editForm =
+		availableUpdateForms.find((form) => form.slug === formSlug) ||
+		availableUpdateForms.find((form) => form.isDefault) ||
+		availableUpdateForms[0];
+
+	const editQuery = editForm.isDefault ? "" : `?form=${editForm.slug}`;
+
```
Comment (tefkah) [inline core/app/c/[communitySlug]/pubs/[pubId]/page.tsx:217]: new: make the "update" button on the view page redirect to the same form you're viewing rn, if you have access to it

File: core/app/components/DataTable/PubsDataTable/PubsDataTableClient.tsx [hunk 4]
```diff
@@ -51,47 +51,38 @@ export const PubsDataTable = ({ perPage, ...props }: PubsDataTableProps) => {
...
-				communitySlug: community.slug,
-			},
-		},
-	});
-
+	filterParams,
+	setFilterParams,
+	data,
+	isLoading,
+}: PubsDataTableClientBaseProps) => {
```
Comment (tefkah) [inline core/app/components/DataTable/PubsDataTable/PubsDataTableClient.tsx:85]: ive split this up so we can reuse it for the form table

File: core/lib/api.ts [hunk 5]
```diff
@@ -7,3 +7,18 @@ import { env } from "./env/env";
...
+		return failureCount < RETRY_COUNT;
+	}
+
+	if (error.status >= 400 && error.status < 500) {
+		// unlikely such an error would resolve itself, so don't retry
+		return false;
+	}
+
+	return failureCount < RETRY_COUNT;
+};
```
Comment (tefkah) [inline core/lib/api.ts:24]: By default ReactQuery retries a query up to three times if it fails, but the new forms route throws a 400 if the thing is not working properly and therefore it will retry it a bunch of times. In general, I don't think it makes sense to retry on a 400 or higher, so i added this custom retry policy

File: core/prisma/seed/seedCommunity.ts
Comment (tefkah) [inline core/prisma/seed/seedCommunity.ts:1]: general changes here:
- set the the relationconfig properly
- make it possible (and required) to set relatedPubTypes for a relation form element
- make it possible to assign users a specific form in the seed

File: packages/contracts/src/resources/site.ts
Comment (tefkah) [inline packages/contracts/src/resources/site.ts:1]: extracted bc i at first had another file called `forms.ts`, but reverted that. 
i do think it's a bit nicer to have it separated, so i kept it

File: core/app/components/pubs/InitialCreatePubForm.tsx [hunk 6]
```diff
@@ -192,17 +193,14 @@ export const InitialCreatePubForm = ({
...
-						)}
-					</Button>
+					<FormSubmitButton
+						formState={form.formState}
+						disabled={!form.formState.isValid}
+						idleText="Create Pub"
+						successText="Redirecting..."
+						pendingText="Redirecting..."
+						isSubmitting={form.formState.isSubmitSuccessful}
+					/>
```
Comment (tefkah) [inline core/app/components/pubs/InitialCreatePubForm.tsx:203]: slightly nicer loading experience here
