### PR TITLE
fix: better experience for contributors

### LINKED ISSUE #1300: Clean up UI for contributor users
## Motivation

So users who experience PubPub as contributors have a better, less confusing experience

## Requirements

- For contributor users, remove links to All Workflows on sidebar
- For contributor and editor users, remove link to "Manage Types" on the All Pubs Page
- For all users, All Pubs page should only show pagination results based on Pubs they have access to not, currently, for the entire community, as it seems to do.
- For all users, if they only have access to one community, the community dropdown icon should not be usable or should not show

### LINKED ISSUE #1301: Do not allow contributor users to take actions on pubs directly
## Motivation

So contributor users can't trigger actions. I believe this is what we had settled on (https://github.com/pubpub/platform/issues/656), but appears to have been a bit lost in translation, as contributor users can still take actions on Pubs (or at least see the actions on Pub cards and open their popups)

## Requirements

Removes the ability for contributor members (at any level) to take actions on Pubs directly, so that they can't access admin features.

### PR DESCRIPTION
**Pull request by tefkah**
- **fix: dont let users  see create pub/manage types button if they cant**
- **fix: dont let users see remove/edit/run pub buttons on card if they cant**
- **fix: make sure users see correct things on pub detail page**

## Issue(s) Resolved

Resolves #1301 
Resolves #1300 

## High-level Explanation of PR

https://github.com/user-attachments/assets/3515cb2f-e794-4ffa-985f-ff37d0a29534

https://github.com/user-attachments/assets/d46159fa-141a-45a6-83d1-9cd5f4407a9d

## Screenshots (if applicable)

If user isnt able to move or see this stage, then the drop down doesn't appear
image

### if user does not have access to any relations, show message

before:
image

after:
image

after if only some pubs are visible:
image

### CODE REVIEW

File: core/app/c/[communitySlug]/pubs/PubList.tsx [hunk 1]
```diff
@@ -94,23 +120,22 @@ const PubListFooterPagination = async (props: {
...
+		{ communityId: props.communityId, userId: props.userId },
+		{
+			search: query,
+		}
+	);
+
+	const paginationProps = {
+		mode: "total" as const,
+		totalPages: Math.ceil((count ?? 0) / perPage),
+	};
```
Comment (tefkah) [inline core/app/c/[communitySlug]/pubs/PubList.tsx:138]: i initially added some different type of pagination for search queries bc we couldnt count the total number of results. we can now, so we always do the normal pagination

File: core/app/c/[communitySlug]/pubs/[pubId]/page.tsx [hunk 2]
```diff
@@ -187,18 +189,22 @@ export default async function Page(props: {
...
+						>
+							<Link href={`/c/${communitySlug}/pubs/${pub.id}/edit`}>
+								<Pencil size="12" />
+								<span>Update</span>
+							</Link>
+						</Button>
+					)}
+					{canArchive && (
+						<RemovePubButton pubId={pub.id} redirectTo={`/c/${communitySlug}/pubs`} />
+					)}
```
Comment (tefkah) [inline core/app/c/[communitySlug]/pubs/[pubId]/page.tsx:207]: wow actual checks??

File: core/app/components/PubCard.tsx
[the remark this answers is not in the document]
Comment (tefkah) [reply core/app/components/PubCard.tsx:1]: this can lead to a ton of db requests, like 5x the number of cards. locally this doesn't seem to be a problem, but we should keep an eye out for any perf regressions.

File: core/app/components/pubs/RelationsDropDown.tsx [hunk 3]
```diff
@@ -70,28 +70,44 @@ export const RelationsDropDown = ({ pubId, numRelations }: Props) => {
...
-						);
-					})
+						)}
+					</>
+				) : (
+					<DropdownMenuItem>
+						<p className="w-full text-center text-xs font-medium text-muted-foreground">
+							No related Pubs are visible to you
+						</p>
+					</DropdownMenuItem>
```
Comment (tefkah) [inline core/app/components/pubs/RelationsDropDown.tsx:110]: see screenshots, it was a lil weird to see nothing in the dropdown if you dont have access to the related pubs. maybe we should always show the related pubs anyway, idk

File: core/lib/server/form.ts [hunk 4]
```diff
@@ -48,6 +49,11 @@ export const getForm = (
 					eb("forms.pubTypeId", "=", props.pubTypeId!).and("forms.isDefault", "=", true)
 				)
 			)
+			.$if(Boolean(props.pubId), (eb) =>
+				eb
+					.innerJoin("pubs", "pubs.pubTypeId", "forms.pubTypeId")
+					.where("pubs.id", "=", props.pubId!)
+			)
```
Comment (tefkah) [inline core/lib/server/form.ts:56]: this was to make the pub detail page load faster, now we can get the form and pub at the same time, rather than getting the pub first, then getting the form by its pubtype

File: core/lib/server/pub.ts [hunk 5]
```diff
@@ -1275,6 +1279,21 @@ const DEFAULT_OPTIONS = {
...
+	withRelatedCounts: false,
+	count: true,
+	withPubType: false,
+	withSearchValues: false,
+	withStageActionInstances: false,
+	withMembers: false,
+	withStage: false,
+	trx: db,
+} as const satisfies GetPubsWithRelatedValuesOptions;
+
```
Comment (tefkah) [inline core/lib/server/pub.ts:1296]: if were counting the pubs, we dont want a lot of things, especially relatedpubs

File: core/lib/server/pub.ts [hunk 6]
```diff
@@ -1892,13 +1912,30 @@ export async function getPubsWithRelatedValues<Options extends GetPubsWithRelate
...
 	if (options?._debugDontNest) {
 		// @ts-expect-error We should not accomodate the return type for this option
 		return result;
 	}
 
+	if (options?.count) {
+		// @ts-expect-error We should not accomodate the return type for this option
+		return (result?.[0]?.count ?? 0) as number;
+	}
+
```
[the remark this answers is not in the document]
Comment (tefkah) [reply core/lib/server/pub.ts:1938]: the `where` clause here should be superfluous, but just to be safe

File: core/lib/server/pub.ts [hunk 7]
```diff
@@ -2020,27 +2057,32 @@ export const stagesWhere = <EB extends ExpressionBuilder<any, any>>(
...
+			userId: props.userId,
+		},
+		{ ...opts, limit: 1_000_000, count: true }
+	);
+
+	// @ts-expect-error just trust me its a number
+	const count = pubsCount as number;
 
-	return pubs.count;
+	return count;
```
Comment (tefkah) [inline core/lib/server/pub.ts:2085]: this just wraps the getRelatedPubs func nicely

File: core/playwright/pub.spec.ts [hunk 8]
```diff
@@ -196,10 +203,11 @@ test.describe("Creating a pub", () => {
 		await page.getByLabel("Animals").fill("penguins");
 		await page.keyboard.press("Enter");
 		await page.getByTestId("remove-button").first().click();
+		await page.waitForTimeout(200);
```
Comment (tefkah) [inline core/playwright/pub.spec.ts:206]: this was erroring without this timeout for some reason locally, grrrr

File: core/app/c/[communitySlug]/stages/[stageId]/page.tsx [hunk 9]
```diff
@@ -67,7 +85,15 @@ export default async function Page(props: {
...
 		user.id
 	);
-	const [stage, showEditButton] = await Promise.all([stagePromise, capabilityPromise]);
+	const [{ stage, canViewStage }, showEditButton] = await Promise.all([
+		stagePromise,
+		capabilityPromise,
+	]);
+
+	if (!canViewStage) {
+		// TODO: replace with new nextjs auth interrupts
```
Comment (3mcd) [inline core/app/c/[communitySlug]/stages/[stageId]/page.tsx:94]: Could you explain this TODO a little? Not sure what new NextJS auth interrupts are!

File: core/app/components/PubCard.tsx
[the remark this answers is not in the document]
Comment (3mcd) [reply core/app/components/PubCard.tsx:1]: yeah that was my first thought when I watched your demo video (thanks for those as usual btw). if it's too slow we could always just show 10 pubs and remove the option to set the # of results per page. or show some more optimized version of the page (without all the fancy controls) when the count goes above a certain threshold

File: core/playwright/pub.spec.ts (hunk 8 above)
Comment (3mcd) [reply core/playwright/pub.spec.ts:206]: ez fix. make every request blocking and disable all animations

**Comment by gabestein** [comment]
Lgtm! Thanks very much!

File: core/app/c/[communitySlug]/pubs/page.tsx [hunk 10]
```diff
@@ -23,7 +22,7 @@ export const metadata: Metadata = {
 
 type Props = {
 	params: Promise<{ communitySlug: string }>;
-	searchParams: { [key: string]: string | string[] | undefined };
+	searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
```
[the remark this answers is not in the document]
Comment (tefkah) [reply core/app/c/[communitySlug]/pubs/page.tsx:25]: `searchParams` etc are async since next 15!

https://nextjs.org/docs/messages/sync-dynamic-apis

File: core/app/c/[communitySlug]/stages/[stageId]/page.tsx (hunk 9 above)
Comment (tefkah) [reply core/app/c/[communitySlug]/stages/[stageId]/page.tsx:94]: yeah sorry, it's this: https://nextjs.org/docs/app/api-reference/config/next-config-js/authInterrupts

next introduced the ability to actually "throw" `401`s and `403` using `unauthorized()` and `forbidden()`, a la `notFound()`. i think we should use those instead of this unauthorized page in the future. i started doing that, but thought it would be too much clutter for this pr, so i put that todo there to remind me

**Comment by gabestein** [comment]
Did this make it up? I see the big red x.
