### PR TITLE
Fix stage deletion by removing unused tables

### LINKED ISSUE #632: Unjournal: delete stage
## Motivation
David is unable to delete the "To evaluate" stage in the production Unjournal community.

## Requirements
- Fix an error where attempting to delete a stage results in the message (approx) "Failed to delete move constraints or stages"
- Ensure deleting a stage (and its associated move constraints) works via delete key AND the "Delete this Stage" button on the stage editor panel.

## Who Requested
David / Unjournal

## Optional

This does not happen all the time. _Might_ be an issue specific to this stage, community, or environment.

This has been happening for a while -- before Thomas's prisma->kysely refactor.

### PR DESCRIPTION
**Pull request by kalilsn**
Resolves #632 
## High-level Explanation of PR
The unjournal stages that can't be deleted have a foreign key reference to some unused tables that were intended to track history of assignment and stage movement, but aren't used anymore. Dropping those stages will allow the IDs to be fixed.

- Drops the action_move and action_claim tables
- Sets submit button stage to null if its referenced stage is deleted
	- 	This could be improved by warning the user before deleting the stage, but I had trouble (async/await issues) making that work. Draft PR with my quick attempt [here](https://github.com/pubpub/platform/pull/698).

## Test Plan
- Set a stage on a submit button, then try deleting that stage. It should succeed
- No real way to test the other changes but I'll delete that pesky stage in prod after this is deployed

### CODE REVIEW

File: core/app/c/[communitySlug]/pubs/[pubId]/page.tsx [hunk 1]
```diff
@@ -154,9 +153,6 @@ export default async function Page({
 							) : null}
 						</div>
 					</div>
-					<div>
-						<MembersAvatars pub={pub} />
-					</div>
```
Comment (kalilsn) [inline core/app/c/[communitySlug]/pubs/[pubId]/page.tsx:159]: This wasn't rendering anything on most pubs, and it's confusing when it is rendered. See the "Assigned To" section  on this [pub](https://app.pubpub.org/c/unjournal/pubs/3997773c-d691-415e-a0c4-d4b4f7de29ac)
image

File: core/prisma/schema.prisma
Comment (tefkah) [inline core/prisma/schema.prisma:1]: Very good changes!

**Review by tefkah — APPROVED** [review]
Looks great! I'll have a look at the draft PR to see if that's feasible, but otherwise great work!
