### PR TITLE
Convert form bookmark button to copy link button

### LINKED ISSUE #715: Bookmark from external user form doesn't do anything
### What went wrong, step-by-step?

1. User wants to copy link to form
2. User selects "Bookmark" button at the top of the form
3. Nothing happens

### What did you expect to happen?
User could use bookmark to copy link to this form fill

### What URL can we use to see the issue?
https://app.pubpub.org/c/unjournal/public/forms/eval-form/fill?pubId=d965e55d-8f08-4f00-825e-3d155dcaa97b&token=d49bfd4c-cc68-4f3c-bdad-28e419698aa8.VWdkAs55Z0okqsdhRjCpjQ&reason=expiredToken

### What browser/operating system were you using?
Firefox/Chrome

## Optional
mentioned as "extra work" in #386 

### Have any screenshots? (Attach them by dragging the image here)
Screen Shot 2024-10-15 at 10 36 37 AM

### Who reported this? (If not you)
David/Unjournal

### PR DESCRIPTION
**Pull request by 3mcd**
## Issue(s) Resolved

Resolves #715

## High-level Explanation of PR

This PR changes the previously non-functional bookmark button on the form fill page into a "copy link" button that copies the form URL for easy sharing.

## Test Plan

- Visit the a form fill page.
- Click the copy link.
- Confirm that the page URL was copied.

### CODE REVIEW

File: core/app/c/(public)/[communitySlug]/public/Header.tsx [hunk 1]
```diff
@@ -1,8 +1,8 @@
 import type { ReactNode } from "react";
 
 import { Button } from "ui/button";
-import { Bookmark } from "ui/icon";
 
+import { FormLinkCopyButton } from "~/app/components/forms/FormLinkCopyButton";
```
Comment (allisonking) [inline core/app/c/(public)/[communitySlug]/public/Header.tsx:5]: I think you'll need to dynamically import this or else you'll get "window is not defined" errors on the server:

```
NEXT_RUNTIME is `edge` and NODE_ENV is `development`; skipping OTEL + Sentry registration.
 GET /c/croccroc/public/forms/review/fill 500 in 469ms
 ⨯ core/app/components/forms/FormLinkCopyButton.tsx (9:28) @ FormLinkCopyButton
 ⨯ ReferenceError: window is not defined
    at FormLinkCopyButton (./core/app/components/forms/FormLinkCopyButton.tsx:9:28)
digest: "2216156825"
   7 |
   8 | export const FormLinkCopyButton = (props: Props) => {
>  9 | 	return <CopyButton value={window.location.href} {...props} />;
     | 	                          ^
  10 | };
  11 |
 GET /favicon.ico?favicon.412d60c0.ico 200 in 86ms
```

I had to do the same thing for the [FormCopyButton](https://github.com/pubpub/platform/blob/em/form-copy-link/core/app/c/%5BcommunitySlug%5D/forms/%5BformSlug%5D/edit/page.tsx#L19-L22)

File: core/app/components/forms/FormLinkCopyButton.tsx [hunk 2]
```diff
@@ -0,0 +1,10 @@
+"use client";
+
+import type { CopyButtonProps } from "ui/copy-button";
+import { CopyButton } from "ui/copy-button";
+
+type Props = Omit<CopyButtonProps, "value">;
+
+export const FormLinkCopyButton = (props: Props) => {
```
Comment (allisonking) [inline core/app/components/forms/FormLinkCopyButton.tsx:8]: nit: what do you think about making this a general `CopyCurrentLinkButton` ? since there's nothing in here specific to form linking, so then we can easily reuse it elsewhere too

**Review by allisonking — CHANGES_REQUESTED** [review]
works great, but there's a server error!

File: core/app/components/forms/FormLinkCopyButton.tsx (hunk 2 above)
Comment (3mcd) [reply core/app/components/forms/FormLinkCopyButton.tsx:8]: Great suggestion! I'll do that now.
